# Status_Codes

SUCCESS = 200
BAD_REQUEST = 400
UNAUTHORIZED = 401
FORBIDDEN = 403
NOT_FOUND = 404
METHOD_NOT_ALLOWED = 405
NOT_ACCEPTABLE = 406
REQUEST_TIMEOUT = 408
CONFLICT = 409
GONE = 410
LENGTH_REQUIRED = 411
PRECONDITION_FAILED = 412
CONTENT_TOO_LARGE = 413
URI_TOO_LONG = 414
UNSUPPORTED_MEDIA_TYPE = 415
INTERNAL_SERVER_ERROR = 500
BAD_GATEWAY = 502
SERVICE_UNAVAILABLE = 503
GATEWAY_TIMEOUT = 504
HTTP_VERSION_NOT_SUPPORTED = 505
VARIANT_ALSO_NEGOTIATES = 506
INSUFFICIENT_STORAGE = 507
LOOP_DETECTED = 508
NOT_EXTENDED = 510
NETWORK_AUTHENTICATION_REQUIRED = 511

# Error Messages
EMPTY_FILE = "Empty file"
INVALID_USER_ID = "Invalid user ID"
INVALID_PROJECT_ID = "Invalid project ID"
INVALID_FILE = "Invalid file"
INVALID_LINK = "Invalid link"
INVALID_PATH = "Invalid path"
INVALID_CONTENT = "Invalid content"
INVALID_CONTENT_TYPE = "Invalid content type"
INVALID_CONTENT_LENGTH = "Invalid content length"
INVALID_CONTENT_ENCODING = "Invalid content encoding"
INVALID_CONTENT_DISPOSITION = "Invalid content disposition"
FAILED_TO_DOWNLOAD_LINK_CONTENT = "Failed to download link content"
